### ISSUE TITLE
v2.0.0: failure when running tests with backticks in names

### ISSUE THREAD

**Issue by Akeboshiwind** [codymikol/neotest-kotlin#71]
Hi, I've been trying out v2.0.0. I appreciate you're probably not ready for feedback yet, so feel free to close if this isn't the right time.

I'm unable to run individual tests when the method name uses backticks.

For example:

```kotlin
class MyTest {
    @Test
    fun `my test with spaces`() { // <- cursor here
        1 shouldBe 1
    }
}
```

Running the nearest test from here gives:

<details><summary>Failure</summary >

```
> Task :app:kotlinTest FAILED
iscover(EngineDiscoveryOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
        at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
        at io.github.codymikol.kotlintest.execute.junit.JUnitTestExecutor.run(JUnitTestExecutor.kt:34)
        at io.github.Executing: io.github.codymikol.kotlintest.MainKt execute --classes=org.example.BacktickTest --output=/var/folders/z5/d6frvrd17sl69jpjyyjhlc4w0000gn/T/nvim.osm/TAHcu6/0.json --filter=org.example.BacktickTest::`my test with spaces`
Exception in thread "main" org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.dcodymikol.kotlintest.execute.TestFrameworkExecutor$Companion$runAll$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:67)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$flowOf$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:110)
        at io.github.codymikol.kotlintest.execute.TestFrameworkExecutor$Companion$runAll$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:109)
        at io.github.codymikol.kotlintest.execute.TestFrameworkExecutor$Companion$runAll$1.invokeSuspend(TestFrameworkExecutor.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:94)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:70)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at io.github.codymikol.kotlintest.execute.TestFrameworkExecutor$Companion.runAll(TestFrameworkExecutor.kt:38)
        at io.github.codymikol.kotlintest.command.Execute.run(Execute.ncher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        ... 26 more
Caused by: org.junit.platform.commons.PreconditionViolationException: Could not find method with name [`my test with spaces`] in class [org.example.BacktickTest].
        at org.junit.platform.engine.discovery.MethodSelector.lambda$lazyLoadJavaMethod$2(MethodSelector.java:258)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:256)
        at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:207)
        at org.veryListener.java:39)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
        at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
        at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
        at org.junit.platform.laujunit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:90)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:75)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:150)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.Abstrackt:22)
        at com.github.ajalt.clikt.core.CoreCliktCommandKt.parse(CoreCliktCommand.kt:107)
        at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:78)
        at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:90)
        at io.github.codymikol.kotlintest.MainKt.main(Main.kt:12)
Caused by: org.junit.platform.commons.JUnitException: MethodSelector [className = 'org.example.BacktickTest', methodName = '`my test with spaces`', par
ameterTypes = '', classLoader = null] resolution failed
        at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscotPipeli
ne.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:126)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:92)
        ... 31 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kotlinTest'.
> Process 'command '/Users/osm/.local/share/mise/installs/java/temurin-21.0.9+10.0.LTS/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
4 actionable tasks: 2 executed, 2 up-to-date
```

</details>

The issue is that treesitter captures the name including the backticks (`` `my test with spaces` ``), but the JVM method name doesn't include them so the filter doesn't match.

**Comment by codymikol** [comment]
Thanks for the write up!

**Comment by NickHackman** [comment]
Appreciate the issue! [This should be resolved](https://github.com/codymikol/neotest-kotlin/blob/cf161dbf5817d3251d3903b782f341f4df252c6d/kotlin-test/core/src/test/kotlin/io/github/codymikol/kotlintest/junit/JUnitDiscoveryFunctionalSpec.kt#L63-L110), all discovery of tests has moved from using Treesitter to using the Kotlin Analysis API to parse the tests.

v2.0.0 is still in the works, but we're in a somewhat usable state depending on your use case. For me personally, it doesn't work as of [cf161db](https://github.com/codymikol/neotest-kotlin/commit/cf161dbf5817d3251d3903b782f341f4df252c6d) because of the lack of support for super classes for KoTest, but that's in the works 😄

**Comment by Akeboshiwind** [comment]
Hmm, still not working for me as of f7c3381 FWIW!
I'm now just getting `No tests found` instead

**Comment by NickHackman** [comment]
@Akeboshiwind We're in an intermediate step here when it comes to the plugin that makes setup more involved. Discovery has moved to the Kotlin Gradle plugin itself and we haven't started publishing that to any repositories so you need to make it locally.

```sh
make publish-kotlin-test-locally
```

From there, you should be able to open up the test file (may need to save it or wait ~1 min, it really depends here on how long it takes Gradle to compile the init script and get things going). It should recognize your test (you can also open the test summary here for neotest) and running it should work so long as it doesn't fall under some edge cases we have that need to be ironed out before we're really ready here with a v2.

Let me know if this doesn't work and feel free to open other issues or re-open this one! 😄
